apiVersion: v1
kind: Service
metadata:
  name: rqlite-cluster
spec:
  ports:
  - name: rqlite-http
    port: 4001
    protocol: TCP
    targetPort: 4001
  - name: rqlite-raft
    port: 4002
    protocol: TCP
    targetPort: 4002
  selector:
    run: rqlite
  sessionAffinity: None
  type: ClusterIP

